### ISSUE TITLE
Insertion point

### ISSUE THREAD

**Issue by yuvalt** [giannif/BinarySearch#2]
Would be nice if you could also include a function that will find the index where to insert a new element into the sorted array, if it doesn't exist

**Comment by giannif** [comment]
Yeah, I think I can swing that. Any ideas on what we'd call this function?

**Comment by yuvalt** [comment]
Thanks!  :+1: Maybe binarySearchInsertFor(element) or insertionIndexOf(element) or findInsertionIndexFor(element)?

**Comment by giannif** [comment]
Tough call. We probably should keep it prefaced. But then we loose readability. I'm thinking `binarySearchInsertionIndexFor`. Will mull it over while I write the code.

**Comment by giannif** [comment]
@yuvalt How does the features/insertion-point branch look?

**Comment by yuvalt** [comment]
Looks good! Thanks a lot :+1:  :+1:  :+1:
